### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by helgatheviking**
Customizer support
Some code standards

### CODE REVIEW

**Comment by szepeviktor** [comment]
A plethora of CS fixes! :)

**Comment by helgatheviking** [comment]
Not getting them all this time, but a good start. If you've got a minute to test 2.0 out (customizer support yay!) that would be a big help.

**Comment by szepeviktor** [comment]
`grunt build` fails for me.

kép

**Comment by szepeviktor** [comment]
@helgatheviking Please consider setting up GitHub Actions to run _everything_ on every commit.

**Comment by helgatheviking** [comment]
Oh yeah, I need to set up the build script to transpile the EC6 script which the current js build tools don't seem to like much. Build tools usually kick my butt.

**Comment by szepeviktor** [comment]
If you like "butt-kicking"
I could a PR your way to check everything I know of.
https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/Continuous-integration-Continuous-delivery.md

**Pull request merged**
