### PR TITLE
First half of WPCS

### PR DESCRIPTION
**Pull request by szepeviktor**
Run it

```
composer require --dev wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer
vendor/bin/phpcs
```

inc/class.Walker_Nav_Menu_Edit_Roles_4.7.php and inc/class.Walker_Nav_Menu_Edit_Roles_4.5.php are not done yet.

Please share your feelings!

### CODE REVIEW

**Comment by szepeviktor** [comment]
Git does not really recognizes the two classes as changed! They have been fully WPCS-d :)

**Comment by helgatheviking** [comment]
Thanks for this! I don't have a ton of time to review right now. I'm not thrilled about the mass indenting of everything as that clobbers the git history by touching the entire file. But I'm not sure there's a way around it either. In some places we could "quit early", but in some places that won't work either. Need to think about that...

**Comment by szepeviktor** [comment]
> the mass indenting of everything

Do you mean follow WPCS/WordPress-Core?

How to do that without changing indentations?

**Comment by helgatheviking** [comment]
Yes. You can sometimes do

```
if ( ! class_exists( 'some_class' ) ) {
    return;
}

class some_class {}
```

as a workaround. Learned that from the woman who rights most of the WP phpcs standards code. Just not applicable in all the cases here.

**Comment by szepeviktor** [comment]
Daily I work for SaaS teams and the basic set of tests are

1. syntax check
1. coding standards
1. static analysis

I've started you in that direction! I hope you will finish this PR :)

**Comment by szepeviktor** [comment]
If you would like to start over, this is the command to run on the original files: `vendor/bin/phpcbf`

**Comment by helgatheviking** [comment]
closed in favor of #48

**Comment by szepeviktor** [comment]
Okay.

**Pull request closed without merging**
